export const SELECCIONA_CATEGORIA = 'SELECCIONA_CATEGORIA';
export const SELECCIONA_TRATAMIENTO = 'SELECCIONA_TRATAMIENTO';
export const CANTIDAD_TRATAMIENTO = 'CANTIDAD_TRATAMIENTO';
export const AGREGAR_FILA = 'AGREGAR_FILA'