export const SELECCIONA_CATEGORIA = 'SELECCIONA_CATEGORIA';
export const SELECCIONA_TRATAMIENTO = 'SELECCIONA_TRATAMIENTO';
export const CANTIDAD_TRATAMIENTO = 'CANTIDAD_TRATAMIENTO';
export const AGREGAR_PRESUPUESTO = 'AGREGAR_PRESUPUESTO';
export const AGREGAR_SUBTOTAL = 'AGREGAR_SUBTOTAL';
export const AGREGAR_DESCUENTO = 'AGREGAR_DESCUENTO';